### ISSUE TITLE
Visual style exception

### ISSUE THREAD

**Issue by hfann** [dahall/AeroWizard#80] opened 2019-01-06 17:51 UTC
I use AeroWizard in a Windows Form application that displays a wizard. On the last page, I have a button that displays save as dialog (SaveFileDialog). Before the save as dialog displays, an InvalidOperationException occurs. This only happens on a client's Windows 10 Pro (1809) PC. The client reported that it used to work but the problem occurs when he received updates in December.

I tied to reproduce the error but is unable to do so. My app targets .Net Framework 4 and uses version 2.1.8 of AeroWizard when the error occurred.

I have updated to the latest version but the user still reports the error. I also asked the user to use a different theme but the problem still occurs.

Any change that can avoid this exception will be appreciated.

![tberror](https://user-images.githubusercontent.com/26609186/50739591-c6e01000-11b0-11e9-8b1d-0b586cab90c0.png)

**Comment by dahall** [comment] 2019-01-06 19:16
I believe I have fixed the problem using code working in other parts of the project. Please have the user test and confirm once you've updated to 2.2.1.

**Comment by mwidev** [comment] 2019-01-08 07:34
I had the same issue on OpenFileDialog ShowDialog
It is now fixed. But the Wizard look strange while the FileDialog is Visible:

![image](https://user-images.githubusercontent.com/18728996/50816243-40e2d700-1320-11e9-933a-03ae9a724b00.png)

**Comment by dahall** [comment] 2019-01-08 15:11
@mwidev: With which version are you seeing that black caption? Did you see it on prior versions?

**Comment by mwidev** [comment] 2019-01-08 15:23
I use Windows 10 1809 and AeroWizard version 2.2.1

Am Di., 8. Jan. 2019 um 16:11 Uhr schrieb David Hall <
notifications@github.com>:

**Comment by MatthewBeardmore** [comment] 2019-01-09 18:37
I am experiencing the same issue with 2.2.1 on Windows 10 Version 1809 (OS Build 17763.195). I didn't experience this issue until after updating to the October update.

**Comment by dahall** [comment] 2019-01-09 20:52
I've implemented another fix and am installing 1809 on a VM to test. If testing goes well, I'll have a fix released tonight (v2.2.2).

**Comment by dahall** [comment] 2019-01-09 20:55
@mwidev or @MatthewBeardmore : Do either of you have access to a system experiencing the issue that can test this before I release?

**Comment by MatthewBeardmore** [comment] 2019-01-09 21:37
Hi, yeah, it's my system that actually is experiencing the issue - I can test the release for you.

**Comment by mwidev** [comment] 2019-01-09 21:55
Yes i have a Dev PC for testings as well 👍

**Comment by dahall** [comment] 2019-01-09 23:36
Attached is a zip file that included the VSIX, the NuGet package and all the assemblies. Please use whichever works best for your testing and let me know if the issue is resolved. Thank you for your help. This is working on my 1809 system, so I hope it works on yours' too.
[AeroWizard.zip](https://github.com/dahall/AeroWizard/files/2743002/AeroWizard.zip)

**Comment by MatthewBeardmore** [comment] 2019-01-09 23:50
Unfortunately, no change for me with 2.2.2. Attached is a picture of what I see with 2.2.2 - which happens to be the same as with 2.2.1.

Before clicking on the open dialog button (and after closing the open file dialog):
![image](https://user-images.githubusercontent.com/808932/50936857-69adbe00-143f-11e9-9134-e70346879d99.png)


After clicking on the open dialog button:
![image](https://user-images.githubusercontent.com/808932/50936834-4c78ef80-143f-11e9-832f-4a1d6099ef47.png)

**Comment by dahall** [comment] 2019-01-10 00:05
So it works fine until you show the FileOpenDialog? I'm trying understand how to test on my side.

**Comment by MatthewBeardmore** [comment] 2019-01-10 04:35
It's working great now - thanks so much for all of your work on this. I wouldn't have guessed it would have been such a large change.

**Comment by dahall** [comment] 2019-01-10 04:44
Thanks. 2.2.2 was just pushed to NuGet and the Marketplace.

**Closed by dahall** 2019-01-10 04:44 UTC
